# Generated by Django 4.2.1 on 2023-10-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year_released', models.PositiveIntegerField()),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
    ]
